import "./globals.css";
import Nav from "./auth/nav";
import { Roboto } from "@next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
 
export default function RootLayout({ children }) {
  return (
    <div>
      <Nav />
      <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-red-200`} 
      >{children}</body>
    </div>
  );
}
